version: "3.8"

networks:
  custom-net:

services:
  mysql-container:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - custom-net

  app:
    depends_on:
      - mysql-container
    build: .
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-container:3306/atm?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8001:8001
    networks:
      - custom-net